version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-container
    ports:
      - "5432:5432"
    env_file:
      - ./postgres.env
    networks:
      - internal-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  internal-network:
    driver: bridge

volumes:
  postgres-data:
